### ISSUE TITLE
global index removal

### ISSUE THREAD

**Issue by jjdv** [DarrenPaulWright/dmd-readable#1]
I like (and use) your plugin - thanks for it.
I've just realized you totally removed the global index. I think it's better not to do it for two reasons:
1. Sometimes the index is helpful (my current case ;)).
2. You have an option in `jsdoc2md` not to generate the global index (with: `--global-index-format none`; see [this issue](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/17#issuecomment-72948583)).

Do you think you could consider removing the empty file `global-index.hbs` from partials?

**Comment by DarrenPaulWright** [comment]
Thanks for the thoughtful suggestion! I just created this issue for jsdoc-to-markdown: https://github.com/jsdoc2md/dmd/issues/90. If it's accepted I'd prefer to go that route, where you'd be able to reset the global-index-format option to whatever you want. Then it would still work the way I need it to, but you could configure it to fit your needs.

**Comment by DarrenPaulWright** [comment]
I think I've got a solution, I'll get it in soon. Are you using your own template?

**Comment by DarrenPaulWright** [comment]
Changes are in, I just published 1.0.0. See the readme for details.

**Comment by jjdv** [comment]
Sorry for the long delay. I'm using GitLab interface sparingly and haven't had email notifications put on.
So far I've had needs for quite simple docs so haven't used any template but if there is any need it won't be any problem.

Many thanks for taking my point seriously ;) and for the solution. Best!
